export const filmsInformation = [
  {
    id: 1,
    name: "Jumanji",
    nation: "USA",
    year: "2020",
    img: "assets/images/jmj.jpg",
  },
  {
    id: 2,
    name: "Disaster And Apocalypse",
    nation: "Korea",
    year: "2021",
    img: "assets/images/disaster_and_apocalypse.jpg",
  },
  {
    id: 3,
    name: "Run",
    nation: "USA",
    year: "2020",
    img: "assets/images/run.jpg",
  },
  {
    id: 4,
    name: "Along with the god",
    nation: "Korea",
    year: "2020",
    img: "assets/images/alg.jpg",
  },
  {
    id: 5,
    name: "Start War",
    nation: "USA",
    year: "2020",
    img: "assets/images/starwars.jpg",
  },
  {
    id: 6,
    name: "Avenger:End game",
    nation: "USA",
    year: "2020",
    img: "assets/images/avengers-endgame.jpg",
  },
  {
    id: 7,
    name: "Black Panther",
    nation: "USA",
    year: "2020",
    img: "assets/images/blackparter.jpg",
  },
  {
    id: 8,
    name: "Thor",
    nation: "USA",
    year: "2020",
    img: "assets/images/thor.jpg",
  },
  {
    id: 9,
    name: "Doctor Stranger",
    nation: "USA",
    year: "2020",
    img: "assets/images/dt.jpg",
  },
];
